// Ghana Digital Twin — Simulated Entity Registry
// Real geographic coordinates for Ghana's natural + infrastructure + human-activity entities.

import type { TwinEntity } from "./types";

const now = Date.UTC(2025, 0, 18, 8, 42, 0); // reference "now"
function ago(days: number, hours = 0): string {
  return new Date(now - days * 86400000 - hours * 3600000).toISOString();
}
function v(version: number, days: number, change: string, source: string, confidence: number) {
  return { version, timestamp: ago(days), change, source, confidence };
}

export const ENTITIES: TwinEntity[] = [
  // ===== Natural: Rivers =====
  {
    id: "ent-volta-river",
    kind: "river",
    type: "natural",
    name: "Volta River (lower)",
    regionId: "vol",
    centroid: [0.0, 5.95],
    geometry: [[-0.08, 6.3], [-0.05, 6.1], [0.0, 5.92], [0.03, 5.78]],
    geometryType: "line",
    lengthKm: 88,
    confidence: 0.97,
    source: "HydroSHEDS + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 4),
    version: 142,
    versions: [
      v(142, 0, "Bank shift detected downstream of Akosombo", "Sentinel-2 L2A", 0.93),
      v(141, 6, "Water extent updated (seasonal)", "Sentinel-1 SAR", 0.95),
      v(140, 13, "Sediment plume observed at mouth", "Sentinel-2", 0.88),
    ],
    attributes: { meanDischarge_m3s: 1180, lengthKm: 88, basin: "Volta" },
    tags: ["transboundary", "regulated", "navigable"],
  },
  {
    id: "ent-pra-river",
    kind: "river",
    type: "natural",
    name: "Pra River",
    regionId: "wst",
    centroid: [-1.78, 5.7],
    geometry: [[-2.0, 6.6], [-1.85, 6.2], [-1.78, 5.7], [-1.72, 5.3], [-1.7, 5.12]],
    geometryType: "line",
    lengthKm: 240,
    confidence: 0.95,
    source: "HydroSHEDS + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 6),
    version: 128,
    versions: [
      v(128, 0, "Turbidity anomaly +38% (downstream of mining belt)", "Sentinel-2 B2/B3", 0.86),
      v(127, 5, "Channel morphology updated", "Sentinel-1 SAR", 0.9),
    ],
    attributes: { meanDischarge_m3s: 214, lengthKm: 240, turbidityNTU: 142, basin: "Pra" },
    tags: ["mining-impacted", "turbidity-watch"],
  },
  {
    id: "ent-ankobra-river",
    kind: "river",
    type: "natural",
    name: "Ankobra River",
    regionId: "wst",
    centroid: [-2.18, 5.4],
    geometry: [[-2.35, 6.25], [-2.25, 5.8], [-2.18, 5.4], [-2.13, 4.95]],
    geometryType: "line",
    lengthKm: 190,
    confidence: 0.93,
    source: "HydroSHEDS + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 9),
    version: 119,
    versions: [
      v(119, 0, "Heavy sediment load persisting (galamsey reach)", "Sentinel-2", 0.9),
      v(118, 4, "New tributary diversion detected", "Sentinel-1 SAR", 0.81),
    ],
    attributes: { meanDischarge_m3s: 96, lengthKm: 190, turbidityNTU: 318, basin: "Ankobra" },
    tags: ["mining-impacted", "turbidity-watch", "critical"],
  },
  {
    id: "ent-tano-river",
    kind: "river",
    type: "natural",
    name: "Tano River",
    regionId: "wst",
    centroid: [-2.98, 5.8],
    geometry: [[-3.05, 6.3], [-2.98, 5.8], [-2.95, 5.4], [-2.93, 5.05]],
    geometryType: "line",
    lengthKm: 170,
    confidence: 0.94,
    source: "HydroSHEDS",
    firstObserved: ago(5400),
    lastUpdated: ago(1),
    version: 96,
    versions: [v(96, 1, "Routine seasonal update", "Sentinel-2", 0.92)],
    attributes: { meanDischarge_m3s: 78, lengthKm: 170, basin: "Tano" },
    tags: ["transboundary"],
  },
  {
    id: "ent-densu-river",
    kind: "river",
    type: "natural",
    name: "Densu River",
    regionId: "gar",
    centroid: [-0.45, 5.7],
    geometry: [[-0.75, 6.15], [-0.6, 5.9], [-0.45, 5.7], [-0.32, 5.52]],
    geometryType: "line",
    lengthKm: 116,
    confidence: 0.96,
    source: "HydroSHEDS + OSM",
    firstObserved: ago(5400),
    lastUpdated: ago(2),
    version: 88,
    versions: [v(88, 2, "Reservoir extent refreshed", "Sentinel-2", 0.94)],
    attributes: { meanDischarge_m3s: 12, lengthKm: 116, basin: "Densu" },
    tags: ["water-supply"],
  },
  {
    id: "ent-offin-river",
    kind: "river",
    type: "natural",
    name: "Offin River",
    regionId: "ash",
    centroid: [-1.95, 6.6],
    geometry: [[-2.1, 6.85], [-1.95, 6.6], [-1.8, 6.4]],
    geometryType: "line",
    lengthKm: 165,
    confidence: 0.92,
    source: "HydroSHEDS + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 11),
    version: 104,
    versions: [v(104, 0, "Sediment increase upstream reach", "Sentinel-2", 0.84)],
    attributes: { meanDischarge_m3s: 64, lengthKm: 165, basin: "Pra" },
    tags: ["mining-impacted"],
  },

  // ===== Natural: Lake =====
  {
    id: "ent-lake-volta",
    kind: "lake",
    type: "natural",
    name: "Lake Volta",
    regionId: "vol",
    centroid: [-0.5, 7.6],
    geometry: [
      [-0.15, 6.32], [0.06, 6.46], [0.11, 6.82], [0.05, 7.22], [-0.06, 7.6],
      [-0.2, 8.0], [-0.32, 8.4], [-0.42, 8.76], [-0.58, 8.96], [-0.78, 8.9],
      [-0.82, 8.5], [-0.7, 8.1], [-0.86, 7.8], [-1.06, 7.56], [-1.16, 7.2],
      [-1.02, 6.96], [-0.82, 6.7], [-0.6, 6.46], [-0.35, 6.3],
    ],
    geometryType: "polygon",
    areaKm2: 8502,
    confidence: 0.99,
    source: "Sentinel-2 + SRTM",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 3),
    version: 311,
    versions: [
      v(311, 0, "Surface extent +0.4% (reservoir rise)", "Sentinel-2 NDWI", 0.97),
      v(310, 3, "Water level 84.2m AMSL", "Sentinel-6 + gauge", 0.96),
      v(309, 7, "Algal bloom signature (chlorophyll-a)", "Sentinel-2 B3/B4", 0.82),
    ],
    attributes: { areaKm2: 8502, maxDepth_m: 75, waterLevel_mAMSL: 84.2, volume_km3: 148 },
    tags: ["reservoir", "regulated", "transboundary", "largest-manmade"],
  },

  // ===== Natural: Forests / Protected Areas =====
  {
    id: "ent-mole-np",
    kind: "protected_area",
    type: "administrative",
    name: "Mole National Park",
    regionId: "sav",
    centroid: [-1.83, 9.25],
    geometry: [[-2.05, 9.5], [-1.6, 9.55], [-1.55, 9.05], [-1.9, 8.95], [-2.1, 9.15]],
    geometryType: "polygon",
    areaKm2: 4840,
    confidence: 0.98,
    source: "WDPA + ESA WorldCover",
    firstObserved: ago(5400),
    lastUpdated: ago(1),
    version: 76,
    versions: [v(76, 1, "Canopy density stable (NDVI 0.62)", "Sentinel-2 NDVI", 0.94)],
    attributes: { areaKm2: 4840, iucnCategory: "II", established: 1958 },
    tags: ["national-park", "elephant-habitat", "unesco-tentative"],
  },
  {
    id: "ent-kakum-np",
    kind: "forest",
    type: "natural",
    name: "Kakum National Park",
    regionId: "cen",
    centroid: [-1.39, 5.35],
    areaKm2: 375,
    confidence: 0.97,
    source: "WDPA + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 12),
    version: 64,
    versions: [v(64, 0, "Minor edge encroachment (−0.3 ha)", "Sentinel-2", 0.88)],
    attributes: { areaKm2: 375, iucnCategory: "II" },
    tags: ["national-park", "rainforest", "canopy-walk"],
  },
  {
    id: "ent-atewa-range",
    kind: "forest",
    type: "natural",
    name: "Atewa Range Forest Reserve",
    regionId: "est",
    centroid: [-0.57, 6.22],
    areaKm2: 232,
    confidence: 0.96,
    source: "ESA WorldCover + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 8),
    version: 71,
    versions: [
      v(71, 0, "South slope vegetation loss (−1.8 ha)", "Sentinel-2 NDVI", 0.9),
      v(70, 9, "Bauxite prospecting access track detected", "Sentinel-1 SAR", 0.79),
    ],
    attributes: { areaKm2: 232, elevationMax_m: 740, biodiversity: "high" },
    tags: ["forest-reserve", "watershed-source", "critical-biodiversity", "mining-pressure"],
  },
  {
    id: "ent-ankasa-ca",
    kind: "protected_area",
    type: "administrative",
    name: "Ankasa Conservation Area",
    regionId: "wst",
    centroid: [-2.65, 5.25],
    areaKm2: 509,
    confidence: 0.97,
    source: "WDPA + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(1),
    version: 58,
    versions: [v(58, 1, "Canopy stable", "Sentinel-2", 0.95)],
    attributes: { areaKm2: 509, iucnCategory: "II" },
    tags: ["national-park", "wet-evergreen"],
  },
  {
    id: "ent-bia-np",
    kind: "forest",
    type: "natural",
    name: "Bia National Park",
    regionId: "wnr",
    centroid: [-3.05, 6.4],
    areaKm2: 306,
    confidence: 0.96,
    source: "WDPA + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(2),
    version: 49,
    versions: [v(49, 2, "Edge stable", "Sentinel-2", 0.93)],
    attributes: { areaKm2: 306, iucnCategory: "II" },
    tags: ["national-park", "biosphere"],
  },

  // ===== Infrastructure: Dams =====
  {
    id: "ent-akosombo-dam",
    kind: "dam",
    type: "infrastructure",
    name: "Akosombo Dam",
    regionId: "est",
    centroid: [0.05, 6.3],
    areaKm2: 1.2,
    confidence: 0.99,
    source: "OSM + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(3),
    version: 42,
    versions: [v(42, 3, "Spillway status updated", "Sentinel-2", 0.95)],
    attributes: { installedMW: 1020, height_m: 134, commissioned: 1965, operator: "VRA" },
    tags: ["hydropower", "national-critical"],
  },
  {
    id: "ent-kpong-dam",
    kind: "dam",
    type: "infrastructure",
    name: "Kpong Dam",
    regionId: "est",
    centroid: [0.07, 6.15],
    areaKm2: 0.6,
    confidence: 0.99,
    source: "OSM + Sentinel-2",
    firstObserved: ago(5400),
    lastUpdated: ago(3),
    version: 38,
    versions: [v(38, 3, "Status nominal", "Sentinel-2", 0.96)],
    attributes: { installedMW: 160, commissioned: 1982, operator: "VRA" },
    tags: ["hydropower"],
  },

  // ===== Infrastructure: Roads =====
  {
    id: "ent-n1-coastal",
    kind: "road",
    type: "infrastructure",
    name: "N1 Trans-West African Coastal Hwy",
    regionId: "gar",
    centroid: [-0.4, 5.5],
    geometry: [[-1.78, 4.9], [-1.4, 5.1], [-1.25, 5.31], [-0.95, 5.45], [-0.5, 5.52], [-0.2, 5.6], [0.0, 5.67], [0.5, 5.7], [1.0, 5.8], [1.28, 5.95]],
    geometryType: "line",
    lengthKm: 540,
    confidence: 0.98,
    source: "OpenStreetMap",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 5),
    version: 167,
    versions: [v(167, 0, "Surface reflectance updated", "Sentinel-2", 0.97)],
    attributes: { lengthKm: 540, class: "trunk", lanes: 2 },
    tags: ["trans-west-african", "primary"],
  },
  {
    id: "ent-n6-accra-kumasi",
    kind: "road",
    type: "infrastructure",
    name: "N6 Accra–Kumasi",
    regionId: "est",
    centroid: [-0.9, 6.2],
    geometry: [[-0.2, 5.6], [-0.35, 5.9], [-0.6, 6.2], [-0.9, 6.3], [-1.3, 6.5], [-1.62, 6.74]],
    geometryType: "line",
    lengthKm: 250,
    confidence: 0.97,
    source: "OpenStreetMap",
    firstObserved: ago(5400),
    lastUpdated: ago(1),
    version: 134,
    versions: [v(134, 1, "Geometry refreshed", "OSM", 0.97)],
    attributes: { lengthKm: 250, class: "primary" },
    tags: ["primary"],
  },
  {
    id: "ent-n10-kumasi-tamale",
    kind: "road",
    type: "infrastructure",
    name: "N10 Kumasi–Tamale",
    regionId: "nor",
    centroid: [-1.0, 8.0],
    geometry: [[-1.62, 6.74], [-1.55, 7.2], [-1.2, 7.75], [-1.0, 8.3], [-0.84, 9.4]],
    geometryType: "line",
    lengthKm: 416,
    confidence: 0.96,
    source: "OpenStreetMap",
    firstObserved: ago(5400),
    lastUpdated: ago(2),
    version: 121,
    versions: [v(121, 2, "Section near Techiman realigned", "OSM + Sentinel-2", 0.93)],
    attributes: { lengthKm: 416, class: "primary" },
    tags: ["primary", "north-south"],
  },

  // ===== Infrastructure: Settlements =====
  ...[
    { id: "ent-accra", name: "Accra", reg: "gar", c: [-0.19, 5.56], pop: 2291352 },
    { id: "ent-kumasi", name: "Kumasi", reg: "ash", c: [-1.62, 6.69], pop: 2069350 },
    { id: "ent-tamale", name: "Tamale", reg: "nor", c: [-0.84, 9.4], pop: 360579 },
    { id: "ent-takoradi", name: "Sekondi-Takoradi", reg: "wst", c: [-1.78, 4.9], pop: 445205 },
    { id: "ent-sunyani", name: "Sunyani", reg: "bon", c: [-2.33, 7.33], pop: 87410 },
    { id: "ent-bolgatanga", name: "Bolgatanga", reg: "upe", c: [-0.85, 10.78], pop: 131011 },
    { id: "ent-wa", name: "Wa", reg: "upw", c: [-2.5, 10.06], pop: 107214 },
    { id: "ent-capecoast", name: "Cape Coast", reg: "cen", c: [-1.25, 5.11], pop: 169894 },
    { id: "ent-koforidua", name: "Koforidua", reg: "est", c: [-0.26, 6.08], pop: 120971 },
    { id: "ent-ho", name: "Ho", reg: "vol", c: [0.47, 6.6], pop: 104532 },
    { id: "ent-techiman", name: "Techiman", reg: "bne", c: [-1.94, 7.58], pop: 104839 },
    { id: "ent-tema", name: "Tema", reg: "gar", c: [0.02, 5.67], pop: 369282 },
  ].map((s) => ({
    id: s.id,
    kind: "settlement" as const,
    type: "infrastructure" as const,
    name: s.name,
    regionId: s.reg,
    centroid: s.c as [number, number],
    geometryType: "point" as const,
    areaKm2: Math.round(s.pop / 3500),
    confidence: 0.97,
    source: "OSM + GH Statistical Service",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 7),
    version: 88,
    versions: [v(88, 0, "Built-up extent +0.6%", "Sentinel-2 + Dynamic World", 0.94)],
    attributes: { population: s.pop, builtUpHa: Math.round(s.pop / 35) },
    tags: ["urban", "population-center"],
  })),

  // ===== Human Activity: Mining / Excavation =====
  {
    id: "ent-obuasi-mine",
    kind: "quarry",
    type: "human_activity",
    name: "Obuasi Mine Complex",
    regionId: "ash",
    centroid: [-1.67, 6.2],
    geometry: [[-1.72, 6.24], [-1.62, 6.24], [-1.62, 6.16], [-1.72, 6.16]],
    geometryType: "polygon",
    areaKm2: 38.4,
    confidence: 0.96,
    source: "Sentinel-2 + Sentinel-1",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 10),
    version: 152,
    versions: [
      v(152, 0, "Active surface disturbance +2.1 ha", "Sentinel-2 NBR", 0.91),
      v(151, 6, "Pit expansion north", "Sentinel-1 SAR", 0.88),
    ],
    attributes: { commodity: "gold", operator: "AngloGold Ashanti", areaKm2: 38.4 },
    tags: ["large-scale-mining", "gold"],
  },
  {
    id: "ent-tarkwa-mine",
    kind: "quarry",
    type: "human_activity",
    name: "Tarkwa Mine",
    regionId: "wst",
    centroid: [-1.98, 5.3],
    geometry: [[-2.02, 5.33], [-1.94, 5.33], [-1.94, 5.27], [-2.02, 5.27]],
    geometryType: "polygon",
    areaKm2: 24.8,
    confidence: 0.95,
    source: "Sentinel-2 + Sentinel-1",
    firstObserved: ago(5400),
    lastUpdated: ago(0, 11),
    version: 138,
    versions: [v(138, 0, "Surface disturbance +1.4 ha", "Sentinel-2 NBR", 0.9)],
    attributes: { commodity: "gold", operator: "Gold Fields", areaKm2: 24.8 },
    tags: ["large-scale-mining", "gold"],
  },
  {
    id: "ent-prestea-galamsey",
    kind: "excavation",
    type: "human_activity",
    name: "Prestea–Huni Valley Galamsey Field",
    regionId: "wst",
    centroid: [-2.14, 5.43],
    geometry: [[-2.2, 5.47], [-2.08, 5.47], [-2.08, 5.39], [-2.2, 5.39]],
    geometryType: "polygon",
    areaKm2: 12.6,
    confidence: 0.84,
    source: "Sentinel-2 + Sentinel-1",
    firstObserved: ago(820),
    lastUpdated: ago(0, 5),
    version: 97,
    versions: [
      v(97, 0, "New excavation clusters (4 pits) detected", "Sentinel-2 + CV model", 0.82),
      v(96, 2, "Expansion +3.2 ha along river buffer", "Sentinel-1 SAR", 0.79),
    ],
    attributes: { commodity: "gold", tenure: "unlicensed", areaKm2: 12.6, pits: 41 },
    tags: ["artisanal-mining", "galamsey", "unlicensed", "river-buffer"],
  },
  {
    id: "ent-bogoso-galamsey",
    kind: "excavation",
    type: "human_activity",
    name: "Bogoso Galamsey Reach",
    regionId: "wst",
    centroid: [-2.0, 5.55],
    areaKm2: 7.1,
    confidence: 0.81,
    source: "Sentinel-2 + Sentinel-1",
    firstObserved: ago(640),
    lastUpdated: ago(0, 7),
    version: 74,
    versions: [v(74, 0, "Active disturbance along Ankobra tributary", "Sentinel-2", 0.8)],
    attributes: { commodity: "gold", tenure: "unlicensed", areaKm2: 7.1, pits: 23 },
    tags: ["artisanal-mining", "galamsey", "unlicensed"],
  },
  {
    id: "ent-akyem-mine",
    kind: "quarry",
    type: "human_activity",
    name: "Akyem Mine",
    regionId: "est",
    centroid: [-1.0, 6.15],
    areaKm2: 19.2,
    confidence: 0.94,
    source: "Sentinel-2 + Sentinel-1",
    firstObserved: ago(1600),
    lastUpdated: ago(1),
    version: 86,
    versions: [v(86, 1, "Reclamation progress +1.0 ha", "Sentinel-2 NDVI", 0.9)],
    attributes: { commodity: "gold", operator: "Newmont", areaKm2: 19.2 },
    tags: ["large-scale-mining", "gold", "reclamation"],
  },

  // ===== Mined water bodies (created by excavation) =====
  {
    id: "ent-prestea-mined-pond",
    kind: "waterbody_mined",
    type: "human_activity",
    name: "Prestea Mined Water Body",
    regionId: "wst",
    centroid: [-2.155, 5.435],
    areaKm2: 0.94,
    confidence: 0.87,
    source: "Sentinel-2 NDWI",
    firstObserved: ago(210),
    lastUpdated: ago(0, 5),
    version: 41,
    versions: [
      v(41, 0, "Water extent +0.12 ha (pit flooding)", "Sentinel-2 NDWI", 0.86),
      v(40, 9, "Initial detection", "Sentinel-2", 0.78),
    ],
    attributes: { origin: "excavation", turbidityNTU: 540, areaKm2: 0.94 },
    tags: ["mining-derived", "turbid", "water-quality-critical"],
  },

  // ===== Watershed =====
  {
    id: "ent-pra-watershed",
    kind: "watershed",
    type: "natural",
    name: "Pra River Watershed",
    regionId: "wst",
    centroid: [-1.6, 6.1],
    areaKm2: 23170,
    confidence: 0.95,
    source: "HydroSHEDS",
    firstObserved: ago(5400),
    lastUpdated: ago(7),
    version: 33,
    versions: [v(33, 7, "Sub-basin delineation refresh", "HydroSHEDS", 0.95)],
    attributes: { areaKm2: 23170, meanRunoff_mm: 410 },
    tags: ["watershed", "mining-impacted"],
  },
];

export function entityById(id: string): TwinEntity | undefined {
  return ENTITIES.find((e) => e.id === id);
}
