// Ghana Digital Twin — Observations (change-detection primitives)
// Each Observation is objective evidence of a physical-world change. No legal conclusions.

import type { Observation } from "./types";

const now = Date.UTC(2025, 0, 18, 8, 42, 0);
function ago(days: number, hours = 0): string {
  return new Date(now - days * 86400000 - hours * 3600000).toISOString();
}

export const OBSERVATIONS: Observation[] = [
  {
    id: "obs-2841",
    type: "excavation_signature",
    title: "New excavation clusters on Ankobra floodplain",
    summary:
      "Four new surface-disturbance pits appeared within 200 m of the Ankobra river channel, with characteristic convex spoil piles and access tracks visible in SAR backscatter.",
    location: [-2.143, 5.428],
    regionId: "wst",
    timestamp: ago(0, 5),
    detectedAt: ago(0, 5),
    affectedEntities: ["ent-prestea-galamsey", "ent-ankobra-river", "ent-prestea-mined-pond"],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD", "Dynamic World"],
    confidence: 0.82,
    status: "active",
    severity: "critical",
    areaAffectedHa: 3.2,
    modelVersion: "gdt-cv-excav-v4.2",
    pipeline: "sar-optical-fusion → segmentation → change-vector",
    reasoning:
      "SAR coherence drop (0.42) co-located with optical bare-soil gain; pit geometry matches learned excavation signature (convex spoil, flooded center). Water body expansion +0.12 ha confirms active digging.",
    attributes: { pits: 4, riverBuffer_m: 180, coherenceDrop: 0.42, bareSoilGain_ndvi: 0.31 },
    evidence: [
      { dataset: "Sentinel-1 GRD", date: ago(0, 5), bands: "VV+VH", confidence: 0.84 },
      { dataset: "Sentinel-2 L2A", date: ago(0, 6), bands: "B2,B3,B4,B8,B11", confidence: 0.83 },
      { dataset: "Dynamic World", date: ago(0, 6), bands: "bare", confidence: 0.78 },
    ],
    beforeDate: ago(7),
    afterDate: ago(0, 6),
  },
  {
    id: "obs-2840",
    type: "water_discoloration",
    title: "Ankobra River turbidity surge downstream of Prestea",
    summary:
      "Spectral turbidity proxy (Rrs_B3/Rrs_B2) increased 38% over a 12 km reach downstream of the Prestea mining field, consistent with suspended sediment loading.",
    location: [-2.16, 5.39],
    regionId: "wst",
    timestamp: ago(0, 6),
    detectedAt: ago(0, 6),
    affectedEntities: ["ent-ankobra-river", "ent-prestea-galamsey"],
    supportingDatasets: ["Sentinel-2 L2A"],
    confidence: 0.86,
    status: "active",
    severity: "high",
    areaAffectedHa: 96,
    modelVersion: "gdt-hydro-turb-v2.1",
    pipeline: "L2A → AC → turbidity-index → temporal-zscore",
    reasoning:
      "Turbidity index z-score = +3.1 (7-day baseline). Plume originates at galamsey reach and dissipates 12 km downstream; no rainfall trigger in prior 72 h (CHIRPS), supporting anthropogenic origin.",
    attributes: { turbidityIndex: 0.74, zScore: 3.1, reachKm: 12, rainfall72h_mm: 2.1 },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(0, 6), bands: "B2,B3", confidence: 0.87 },
      { dataset: "CHIRPS rainfall", date: ago(3), confidence: 0.9 },
    ],
    beforeDate: ago(14),
    afterDate: ago(0, 6),
  },
  {
    id: "obs-2839",
    type: "vegetation_loss",
    title: "Canopy loss on Atewa Range south slope",
    summary:
      "NDVI decline of 0.21 over 1.8 ha of closed-canopy forest on the south slope of the Atewa Range, co-located with a newly detected access track.",
    location: [-0.585, 6.215],
    regionId: "est",
    timestamp: ago(0, 8),
    detectedAt: ago(0, 8),
    affectedEntities: ["ent-atewa-range"],
    supportingDatasets: ["Sentinel-2 L2A", "Global Forest Change", "Sentinel-1 GRD"],
    confidence: 0.9,
    status: "monitoring",
    severity: "high",
    areaAffectedHa: 1.8,
    modelVersion: "gdt-cv-defor-v3.4",
    pipeline: "NDVI → NBR → temporal-break → CV confirm",
    reasoning:
      "Break-for-additive-trend detected on NDVI series; NBR confirms burn/clear signal. New 320 m track visible in SAR leading to clearing edge. Forest reserve boundary crossed.",
    attributes: { ndviDecline: 0.21, nbrDecline: 0.34, trackLength_m: 320, inReserve: true },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(0, 8), bands: "B4,B8,B11", confidence: 0.91 },
      { dataset: "Global Forest Change", date: ago(1), confidence: 0.86 },
      { dataset: "Sentinel-1 GRD", date: ago(0, 9), bands: "VV", confidence: 0.83 },
    ],
    beforeDate: ago(30),
    afterDate: ago(0, 8),
  },
  {
    id: "obs-2838",
    type: "new_waterbody",
    title: "New mining-derived water body near Bogoso",
    summary:
      "A 0.34 ha water body appeared where bare soil existed 16 days prior, exhibiting high turbidity signature consistent with a flooded excavation pit.",
    location: [-2.003, 5.552],
    regionId: "wst",
    timestamp: ago(0, 11),
    detectedAt: ago(0, 11),
    affectedEntities: ["ent-bogoso-galamsey"],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD"],
    confidence: 0.81,
    status: "active",
    severity: "high",
    areaAffectedHa: 0.34,
    modelVersion: "gdt-cv-water-v3.1",
    pipeline: "NDWI → SAR-flood → persistence-filter",
    reasoning:
      "NDWI threshold crossed (0.12→0.41); SAR shows dark (smooth) backscatter confirming open water. High B3 reflectance indicates turbid, not clear, water — pattern matches mined pit flooding.",
    attributes: { areaHa: 0.34, ndwi: 0.41, priorLandcover: "bare", turbid: true },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(0, 11), bands: "B3,B8", confidence: 0.82 },
      { dataset: "Sentinel-1 GRD", date: ago(0, 12), bands: "VV", confidence: 0.8 },
    ],
    beforeDate: ago(16),
    afterDate: ago(0, 11),
  },
  {
    id: "obs-2837",
    type: "surface_disturbance",
    title: "Pit expansion at Obuasi mine complex (north)",
    summary:
      "Surface disturbance increased 2.1 ha on the northern boundary of the Obuasi mine complex, with pit edge advance of ~120 m.",
    location: [-1.668, 6.23],
    regionId: "ash",
    timestamp: ago(0, 13),
    detectedAt: ago(0, 13),
    affectedEntities: ["ent-obuasi-mine"],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD"],
    confidence: 0.91,
    status: "monitoring",
    severity: "moderate",
    areaAffectedHa: 2.1,
    modelVersion: "gdt-cv-excav-v4.2",
    pipeline: "sar-optical-fusion → segmentation → change-vector",
    reasoning:
      "Bare-soil class expanded 2.1 ha; pit edge geometry advanced northward by 120 m (sub-pixel confirmed via SAR coherence). Within licensed concession boundary — disturbance attributed to permitted operation.",
    attributes: { areaHa: 2.1, edgeAdvance_m: 120, withinConcession: true },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(0, 13), bands: "B2,B8,B11", confidence: 0.92 },
      { dataset: "Sentinel-1 GRD", date: ago(0, 14), bands: "VV+VH", confidence: 0.89 },
    ],
    beforeDate: ago(12),
    afterDate: ago(0, 13),
  },
  {
    id: "obs-2836",
    type: "new_road",
    title: "New unpaved road into Bia forest reserve buffer",
    summary:
      "A 2.4 km unpaved road appeared in the buffer zone east of Bia National Park, with associated 0.6 ha clearing at its terminus.",
    location: [-3.01, 6.39],
    regionId: "wnr",
    timestamp: ago(1),
    detectedAt: ago(1),
    affectedEntities: ["ent-bia-np"],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD", "OSM"],
    confidence: 0.85,
    status: "active",
    severity: "moderate",
    areaAffectedHa: 3.0,
    modelVersion: "gdt-cv-road-v2.7",
    pipeline: "line-detector → SAR-ridge → OSM-diff",
    reasoning:
      "Linear feature 2.4 km not present in OSM or prior imagery; SAR ridge-filter confirms compacted surface. Terminal clearing 0.6 ha suggests logging or access purpose. Road terminates 400 m from reserve boundary.",
    attributes: { lengthKm: 2.4, clearingHa: 0.6, distanceToReserve_m: 400 },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(1), bands: "B4,B8", confidence: 0.86 },
      { dataset: "Sentinel-1 GRD", date: ago(1), bands: "VV", confidence: 0.84 },
      { dataset: "OpenStreetMap", date: ago(2), confidence: 0.95 },
    ],
    beforeDate: ago(20),
    afterDate: ago(1),
  },
  {
    id: "obs-2835",
    type: "settlement_growth",
    title: "Accra built-up expansion (northern fringe)",
    summary:
      "Built-up area expanded 14.6 ha on the northern fringe of Accra (Amasaman corridor) over 30 days, converting mixed-agriculture land cover.",
    location: [-0.27, 5.68],
    regionId: "gar",
    timestamp: ago(1),
    detectedAt: ago(1),
    affectedEntities: ["ent-accra"],
    supportingDatasets: ["Sentinel-2 L2A", "Dynamic World"],
    confidence: 0.93,
    status: "monitoring",
    severity: "low",
    areaAffectedHa: 14.6,
    modelVersion: "gdt-cv-builtup-v3.0",
    pipeline: "Dynamic World → built-class aggregation → temporal-diff",
    reasoning:
      "Dynamic World 'built' class increased 14.6 ha; confirmed by optical texture. Consistent with peri-urban growth trend (+8.2% annual for this corridor). No protected-area overlap.",
    attributes: { areaHa: 14.6, priorLandcover: "cultivated", annualTrendPct: 8.2 },
    evidence: [
      { dataset: "Dynamic World", date: ago(1), confidence: 0.92 },
      { dataset: "Sentinel-2 L2A", date: ago(1), bands: "B2,B8,B11", confidence: 0.9 },
    ],
    beforeDate: ago(30),
    afterDate: ago(1),
  },
  {
    id: "obs-2834",
    type: "river_morphology",
    title: "Volta River channel migration (lower reach)",
    summary:
      "Lateral channel shift of 38 m detected over a 1.4 km reach downstream of Akosombo, with bar accretion on the east bank.",
    location: [-0.02, 5.88],
    regionId: "vol",
    timestamp: ago(1),
    detectedAt: ago(1),
    affectedEntities: ["ent-volta-river", "ent-akosombo-dam"],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD"],
    confidence: 0.88,
    status: "monitoring",
    severity: "low",
    areaAffectedHa: 5.3,
    modelVersion: "gdt-hydro-morph-v1.6",
    pipeline: "watermask → centerline → DSAS-shift",
    reasoning:
      "NDWI-derived water mask shows east-bank accretion (−38 m) and west-bank erosion. Magnitude within seasonal range; flagged for continued monitoring as it approaches cultivated land.",
    attributes: { shift_m: 38, reachKm: 1.4, accretionBank: "east", seasonalExpected: true },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(1), bands: "B3,B8", confidence: 0.88 },
      { dataset: "Sentinel-1 GRD", date: ago(2), bands: "VV", confidence: 0.84 },
    ],
    beforeDate: ago(60),
    afterDate: ago(1),
  },
  {
    id: "obs-2833",
    type: "shoreline_change",
    title: "Coastline erosion east of Cape Coast",
    summary:
      "Shoreline retreated 11 m (avg) over a 2.1 km coastal stretch east of Cape Coast, continuing a multi-year erosional trend.",
    location: [-1.18, 5.09],
    regionId: "cen",
    timestamp: ago(2),
    detectedAt: ago(2),
    affectedEntities: ["ent-n1-coastal"],
    supportingDatasets: ["Sentinel-2 L2A", "Copernicus DEM"],
    confidence: 0.87,
    status: "monitoring",
    severity: "moderate",
    areaAffectedHa: 2.3,
    modelVersion: "gdt-coast-shore-v2.0",
    pipeline: "watermask → shoreline → DSAS-transect",
    reasoning:
      "Transect analysis shows −11 m average retreat (max −19 m) vs 90-day baseline. Trend aligns with 4-year retreat pattern; N1 coastal road within 60 m of retreating shoreline at one transect.",
    attributes: { avgRetreat_m: 11, maxRetreat_m: 19, reachKm: 2.1, roadDistance_m: 60 },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(2), bands: "B2,B3,B8", confidence: 0.88 },
      { dataset: "Copernicus DEM", date: ago(90), confidence: 0.85 },
    ],
    beforeDate: ago(90),
    afterDate: ago(2),
  },
  {
    id: "obs-2832",
    type: "land_cover_change",
    title: "Cropland-to-built-up conversion, Kumasi south",
    summary:
      "8.9 ha of cultivated land converted to built-up surface south of Kumasi (Atonsu–Krofofrom corridor).",
    location: [-1.64, 6.62],
    regionId: "ash",
    timestamp: ago(2),
    detectedAt: ago(2),
    affectedEntities: ["ent-kumasi"],
    supportingDatasets: ["Sentinel-2 L2A", "Dynamic World", "ESA WorldCover"],
    confidence: 0.9,
    status: "monitoring",
    severity: "low",
    areaAffectedHa: 8.9,
    modelVersion: "gdt-cv-lcc-v3.2",
    pipeline: "Dynamic World + WorldCover → cross-validated LCC",
    reasoning:
      "Two independent land-cover products agree on cultivated→built transition over 8.9 ha. Texture and spectral signature confirm structures. Consistent with urban sprawl pattern.",
    attributes: { areaHa: 8.9, from: "cultivated", to: "built", productAgreement: 0.91 },
    evidence: [
      { dataset: "Dynamic World", date: ago(2), confidence: 0.9 },
      { dataset: "ESA WorldCover", date: ago(5), confidence: 0.88 },
      { dataset: "Sentinel-2 L2A", date: ago(2), bands: "B4,B8,B11", confidence: 0.89 },
    ],
    beforeDate: ago(45),
    afterDate: ago(2),
  },
  {
    id: "obs-2831",
    type: "deforestation",
    title: "Forest clearing inside Mole NP buffer (west)",
    summary:
      "2.4 ha of wooded savanna cleared in the western buffer of Mole National Park; fire signal absent, indicating mechanical clearing.",
    location: [-2.02, 9.18],
    regionId: "sav",
    timestamp: ago(3),
    detectedAt: ago(3),
    affectedEntities: ["ent-mole-np"],
    supportingDatasets: ["Sentinel-2 L2A", "VIIRS active fire", "Sentinel-1 GRD"],
    confidence: 0.84,
    status: "active",
    severity: "high",
    areaAffectedHa: 2.4,
    modelVersion: "gdt-cv-defor-v3.4",
    pipeline: "NDVI → NBR → fire-mask → CV confirm",
    reasoning:
      "NBR drop 0.28 over 2.4 ha; VIIRS shows no active fire in 30-day window → mechanical clearing. SAR texture confirms bare-soil exposure. Located 700 m outside park boundary in designated buffer.",
    attributes: { areaHa: 2.4, nbrDrop: 0.28, fireSignal: false, distanceToPark_m: 700 },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(3), bands: "B4,B8,B12", confidence: 0.85 },
      { dataset: "VIIRS Active Fire", date: ago(3), confidence: 0.93 },
      { dataset: "Sentinel-1 GRD", date: ago(3), bands: "VV", confidence: 0.82 },
    ],
    beforeDate: ago(30),
    afterDate: ago(3),
  },
  {
    id: "obs-2830",
    type: "construction",
    title: "New large structure footprint near Tema port",
    summary:
      "A 1.6 ha rectangular structure footprint appeared near Tema port expansion zone, consistent with industrial construction.",
    location: [0.01, 5.69],
    regionId: "gar",
    timestamp: ago(3),
    detectedAt: ago(3),
    affectedEntities: ["ent-tema"],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD"],
    confidence: 0.89,
    status: "resolved",
    severity: "low",
    areaAffectedHa: 1.6,
    modelVersion: "gdt-cv-struct-v2.3",
    pipeline: "optical-shadow → rect-detect → SAR-confirm",
    reasoning:
      "Rectangular footprint 1.6 ha with cast-shadow confirmed by sun-angle geometry; SAR double-bounce indicates metallic/structured roof. Located in designated port-industrial zone.",
    attributes: { footprintHa: 1.6, shape: "rectangular", inIndustrialZone: true },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(3), bands: "B2,B4,B8", confidence: 0.9 },
      { dataset: "Sentinel-1 GRD", date: ago(4), bands: "VV+VH", confidence: 0.86 },
    ],
    beforeDate: ago(25),
    afterDate: ago(3),
  },
  {
    id: "obs-2829",
    type: "water_discoloration",
    title: "Pra River turbidity increase at confluence with Offin",
    summary:
      "Turbidity index rose 29% at the Pra–Offin confluence, with plume extending 8 km downstream.",
    location: [-1.82, 6.42],
    regionId: "ash",
    timestamp: ago(3),
    detectedAt: ago(3),
    affectedEntities: ["ent-pra-river", "ent-offin-river", "ent-pra-watershed"],
    supportingDatasets: ["Sentinel-2 L2A"],
    confidence: 0.83,
    status: "monitoring",
    severity: "high",
    areaAffectedHa: 64,
    modelVersion: "gdt-hydro-turb-v2.1",
    pipeline: "L2A → AC → turbidity-index → temporal-zscore",
    reasoning:
      "Turbidity z-score +2.4 at confluence; source signature traces to Offin tributary which passes through mining field. Low rainfall in 72 h window reduces runoff explanation.",
    attributes: { turbidityIndex: 0.61, zScore: 2.4, reachKm: 8, rainfall72h_mm: 4.8 },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(3), bands: "B2,B3", confidence: 0.84 },
      { dataset: "CHIRPS rainfall", date: ago(3), confidence: 0.9 },
    ],
    beforeDate: ago(21),
    afterDate: ago(3),
  },
  {
    id: "obs-2828",
    type: "excavation_signature",
    title: "Reactivated galamsey pits along Tano headwaters",
    summary:
      "Three previously inactive pit clusters show renewed disturbance signature along Tano river headwaters near the western border.",
    location: [-3.04, 6.28],
    regionId: "wnr",
    timestamp: ago(4),
    detectedAt: ago(4),
    affectedEntities: ["ent-tano-river"],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD"],
    confidence: 0.79,
    status: "active",
    severity: "high",
    areaAffectedHa: 1.8,
    modelVersion: "gdt-cv-excav-v4.2",
    pipeline: "sar-optical-fusion → segmentation → change-vector",
    reasoning:
      "SAR coherence dropped at 3 clusters that were stable for 180+ days; optical bare-soil gain confirms reactivation. Pits within 90 m of Tano channel. Transboundary proximity (Côte d'Ivoire) flagged.",
    attributes: { pits: 3, riverBuffer_m: 90, dormantDays: 184, transboundary: true },
    evidence: [
      { dataset: "Sentinel-1 GRD", date: ago(4), bands: "VV+VH", confidence: 0.8 },
      { dataset: "Sentinel-2 L2A", date: ago(4), bands: "B4,B8,B11", confidence: 0.78 },
    ],
    beforeDate: ago(30),
    afterDate: ago(4),
  },
  {
    id: "obs-2827",
    type: "vegetation_loss",
    title: "Savanna degradation near Tamale (south)",
    summary:
      "NDVI decline 0.17 over 22 ha of wooded savanna south of Tamale, likely combined drought + pressure.",
    location: [-0.84, 9.28],
    regionId: "nor",
    timestamp: ago(4),
    detectedAt: ago(4),
    affectedEntities: [],
    supportingDatasets: ["Sentinel-2 L2A", "CHIRPS", "ERA5"],
    confidence: 0.78,
    status: "monitoring",
    severity: "moderate",
    areaAffectedHa: 22,
    modelVersion: "gdt-cv-defor-v3.4",
    pipeline: "NDVI → trend-break → climate-context",
    reasoning:
      "Gradual NDVI decline over 22 ha; rainfall deficit −18% (90-day) and high temperatures support climatic component, but localised pattern suggests anthropogenic pressure叠加. Continued monitoring.",
    attributes: { areaHa: 22, ndviDecline: 0.17, rainfallDeficitPct: -18 },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(4), bands: "B4,B8", confidence: 0.79 },
      { dataset: "CHIRPS", date: ago(5), confidence: 0.88 },
      { dataset: "ERA5", date: ago(5), confidence: 0.9 },
    ],
    beforeDate: ago(90),
    afterDate: ago(4),
  },
  {
    id: "obs-2826",
    type: "surface_disturbance",
    title: "Akyem mine reclamation progress (east)",
    summary:
      "Vegetation recovery on 1.0 ha of previously disturbed mine surface, indicating active reclamation.",
    location: [-0.998, 6.151],
    regionId: "est",
    timestamp: ago(5),
    detectedAt: ago(5),
    affectedEntities: ["ent-akyem-mine"],
    supportingDatasets: ["Sentinel-2 L2A"],
    confidence: 0.9,
    status: "resolved",
    severity: "low",
    areaAffectedHa: 1.0,
    modelVersion: "gdt-cv-reclaim-v1.4",
    pipeline: "NDVI-trend → recovery-signature",
    reasoning:
      "NDVI rose 0.19 over 1.0 ha of former bare surface; spectral signature shifts toward grassland. Consistent with operator-reported reclamation schedule.",
    attributes: { areaHa: 1.0, ndviRise: 0.19, prior: "bare", reclamation: true },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(5), bands: "B4,B8", confidence: 0.9 },
    ],
    beforeDate: ago(60),
    afterDate: ago(5),
  },
  {
    id: "obs-2825",
    type: "new_road",
    title: "Road realignment on N10 near Techiman",
    summary:
      "1.2 km section of N10 realigned near Techiman, with old alignment being decommissioned (vegetation returning).",
    location: [-1.93, 7.59],
    regionId: "bne",
    timestamp: ago(6),
    detectedAt: ago(6),
    affectedEntities: ["ent-n10-kumasi-tamale"],
    supportingDatasets: ["Sentinel-2 L2A", "OpenStreetMap"],
    confidence: 0.92,
    status: "resolved",
    severity: "low",
    areaAffectedHa: 1.2,
    modelVersion: "gdt-cv-road-v2.7",
    pipeline: "line-detector → OSM-diff",
    reasoning:
      "New linear surface (1.2 km) detected parallel to existing N10; old alignment showing NDVI recovery. OSM update confirms realignment. Infrastructure improvement, no environmental concern.",
    attributes: { lengthKm: 1.2, type: "realignment", oldRecovering: true },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(6), bands: "B4,B8", confidence: 0.92 },
      { dataset: "OpenStreetMap", date: ago(6), confidence: 0.94 },
    ],
    beforeDate: ago(40),
    afterDate: ago(6),
  },
  {
    id: "obs-2824",
    type: "construction",
    title: "New building cluster, Wa outskirts",
    summary:
      "0.9 ha of new building footprints on Wa southern outskirts, converting agricultural land.",
    location: [-2.49, 10.03],
    regionId: "upw",
    timestamp: ago(6),
    detectedAt: ago(6),
    affectedEntities: ["ent-wa"],
    supportingDatasets: ["Sentinel-2 L2A", "Dynamic World"],
    confidence: 0.86,
    status: "monitoring",
    severity: "low",
    areaAffectedHa: 0.9,
    modelVersion: "gdt-cv-builtup-v3.0",
    pipeline: "Dynamic World → built-class → texture-confirm",
    reasoning:
      "Built-class expansion 0.9 ha confirmed by structure shadow and texture. Peri-urban growth consistent with regional trend.",
    attributes: { areaHa: 0.9, prior: "cultivated" },
    evidence: [
      { dataset: "Dynamic World", date: ago(6), confidence: 0.85 },
      { dataset: "Sentinel-2 L2A", date: ago(6), bands: "B2,B8", confidence: 0.87 },
    ],
    beforeDate: ago(40),
    afterDate: ago(6),
  },
  {
    id: "obs-2823",
    type: "excavation_signature",
    title: "Quarry expansion near Sunyani",
    summary:
      "Active quarry 6 km west of Sunyani expanded 1.5 ha with characteristic bench-cut signature.",
    location: [-2.42, 7.31],
    regionId: "bon",
    timestamp: ago(7),
    detectedAt: ago(7),
    affectedEntities: [],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD"],
    confidence: 0.85,
    status: "monitoring",
    severity: "moderate",
    areaAffectedHa: 1.5,
    modelVersion: "gdt-cv-excav-v4.2",
    pipeline: "sar-optical-fusion → segmentation",
    reasoning:
      "Bench-cut geometry and convex spoil piles detected; expansion 1.5 ha over 30 days. Within mapped quarry footprint — disturbance attributed to aggregate extraction operation.",
    attributes: { areaHa: 1.5, signature: "bench-cut", withinQuarry: true },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(7), bands: "B4,B8,B11", confidence: 0.86 },
      { dataset: "Sentinel-1 GRD", date: ago(7), bands: "VV", confidence: 0.83 },
    ],
    beforeDate: ago(40),
    afterDate: ago(7),
  },
  {
    id: "obs-2822",
    type: "water_discoloration",
    title: "Lake Volta algal bloom (south basin)",
    summary:
      "Chlorophyll-a proxy elevated over 180 ha of Lake Volta's southern basin, suggesting algal bloom.",
    location: [-0.2, 6.6],
    regionId: "vol",
    timestamp: ago(7),
    detectedAt: ago(7),
    affectedEntities: ["ent-lake-volta"],
    supportingDatasets: ["Sentinel-2 L2A"],
    confidence: 0.8,
    status: "monitoring",
    severity: "moderate",
    areaAffectedHa: 180,
    modelVersion: "gdt-hydro-chla-v1.2",
    pipeline: "L2A → NDCI → bloom-threshold",
    reasoning:
      "NDCI (B5/B4) exceeded bloom threshold over 180 ha; pattern consistent with nutrient loading + warm surface temps. Downstream of agricultural inputs. No toxicity data — flagged for sampling.",
    attributes: { areaHa: 180, ndci: 0.18, sst_c: 29.4 },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(7), bands: "B4,B5", confidence: 0.81 },
    ],
    beforeDate: ago(30),
    afterDate: ago(7),
  },
  {
    id: "obs-2821",
    type: "vegetation_loss",
    title: "Mangrove fringe loss, Ankobra estuary",
    summary:
      "0.8 ha of mangrove fringe lost at the Ankobra estuary, with concurrent shoreline retreat.",
    location: [-2.13, 4.96],
    regionId: "wst",
    timestamp: ago(8),
    detectedAt: ago(8),
    affectedEntities: ["ent-ankobra-river"],
    supportingDatasets: ["Sentinel-2 L2A", "Global Forest Change"],
    confidence: 0.84,
    status: "monitoring",
    severity: "moderate",
    areaAffectedHa: 0.8,
    modelVersion: "gdt-cv-defor-v3.4",
    pipeline: "NDVI → NBR → coastal-mask",
    reasoning:
      "NDVI/NBR decline over mangrove-classified fringe; co-located shoreline retreat suggests combined sediment + clearance pressure. Estuarine nursery habitat impact.",
    attributes: { areaHa: 0.8, ecosystem: "mangrove", shorelineRetreat_m: 6 },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(8), bands: "B3,B4,B8", confidence: 0.85 },
      { dataset: "Global Forest Change", date: ago(8), confidence: 0.82 },
    ],
    beforeDate: ago(60),
    afterDate: ago(8),
  },
  {
    id: "obs-2820",
    type: "land_cover_change",
    title: "Wetland drying, Afram plains",
    summary:
      "42 ha of seasonal wetland shows persistent drying trend in the Afram plains (east of Lake Volta).",
    location: [-0.45, 7.0],
    regionId: "est",
    timestamp: ago(9),
    detectedAt: ago(9),
    affectedEntities: [],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD", "CHIRPS"],
    confidence: 0.77,
    status: "monitoring",
    severity: "moderate",
    areaAffectedHa: 42,
    modelVersion: "gdt-hydro-wet-v1.5",
    pipeline: "NDWI → SAR-flood → persistence-trend",
    reasoning:
      "Wetland water-persistence dropped 31% over 90 days; rainfall near-normal so trend not fully climate-driven. Possible upstream water extraction or channel alteration. Monitoring.",
    attributes: { areaHa: 42, persistenceDropPct: -31, rainfallAnomalyPct: -4 },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(9), bands: "B3,B8", confidence: 0.78 },
      { dataset: "Sentinel-1 GRD", date: ago(10), bands: "VV", confidence: 0.76 },
      { dataset: "CHIRPS", date: ago(9), confidence: 0.88 },
    ],
    beforeDate: ago(90),
    afterDate: ago(9),
  },
  {
    id: "obs-2819",
    type: "new_waterbody",
    title: "Irrigation reservoir expansion, Upper East",
    summary:
      "Small reservoir expanded 0.5 ha near Bolgatanga, consistent with dry-season irrigation development.",
    location: [-0.86, 10.74],
    regionId: "upe",
    timestamp: ago(10),
    detectedAt: ago(10),
    affectedEntities: [],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD"],
    confidence: 0.88,
    status: "resolved",
    severity: "low",
    areaAffectedHa: 0.5,
    modelVersion: "gdt-cv-water-v3.1",
    pipeline: "NDWI → SAR-flood → persistence",
    reasoning:
      "Existing reservoir enlarged 0.5 ha; embankment visible in SAR. Beneficial infrastructure development; no environmental concern flagged.",
    attributes: { areaHa: 0.5, type: "irrigation-reservoir", beneficial: true },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(10), bands: "B3,B8", confidence: 0.88 },
      { dataset: "Sentinel-1 GRD", date: ago(11), bands: "VV", confidence: 0.85 },
    ],
    beforeDate: ago(45),
    afterDate: ago(10),
  },
  {
    id: "obs-2818",
    type: "excavation_signature",
    title: "New pit cluster near Wassa Amenfi",
    summary:
      "Five new excavation pits detected in forest-fringe zone of Wassa Amenfi East, with river-buffer incursion.",
    location: [-2.08, 5.62],
    regionId: "wst",
    timestamp: ago(11),
    detectedAt: ago(11),
    affectedEntities: [],
    supportingDatasets: ["Sentinel-2 L2A", "Sentinel-1 GRD"],
    confidence: 0.81,
    status: "active",
    severity: "critical",
    areaAffectedHa: 4.1,
    modelVersion: "gdt-cv-excav-v4.2",
    pipeline: "sar-optical-fusion → segmentation → change-vector",
    reasoning:
      "5 pit clusters over 4.1 ha; 2 within 150 m of un-named tributary. SAR coherence pattern matches active digging. No licensed concession overlap in cadastre — unlicensed activity signature.",
    attributes: { pits: 5, areaHa: 4.1, riverBuffer_m: 150, concessionOverlap: false },
    evidence: [
      { dataset: "Sentinel-1 GRD", date: ago(11), bands: "VV+VH", confidence: 0.82 },
      { dataset: "Sentinel-2 L2A", date: ago(11), bands: "B2,B4,B8,B11", confidence: 0.8 },
    ],
    beforeDate: ago(30),
    afterDate: ago(11),
  },
  {
    id: "obs-2817",
    type: "deforestation",
    title: "Cocoa farm-to-mine conversion, Ahafo",
    summary:
      "3.6 ha of established cocoa canopy converted to bare/disturbed surface in Ahafo, with excavation signature emerging.",
    location: [-2.54, 6.83],
    regionId: "aha",
    timestamp: ago(12),
    detectedAt: ago(12),
    affectedEntities: [],
    supportingDatasets: ["Sentinel-2 L2A", "Global Forest Change"],
    confidence: 0.83,
    status: "active",
    severity: "high",
    areaAffectedHa: 3.6,
    modelVersion: "gdt-cv-defor-v3.4",
    pipeline: "NDVI → NBR → landcover-confirm",
    reasoning:
      "Canopy loss 3.6 ha where prior land cover was tree-crop (cocoa). Subsequent imagery shows bare soil + pit geometry, indicating conversion to surface mining rather than harvest.",
    attributes: { areaHa: 3.6, prior: "cocoa", conversion: "mining" },
    evidence: [
      { dataset: "Sentinel-2 L2A", date: ago(12), bands: "B4,B8,B11", confidence: 0.84 },
      { dataset: "Global Forest Change", date: ago(12), confidence: 0.82 },
    ],
    beforeDate: ago(60),
    afterDate: ago(12),
  },
];

export function observationById(id: string): Observation | undefined {
  return OBSERVATIONS.find((o) => o.id === id);
}
