// Ghana Digital Twin — Data Source Connectors

import type { DataSource, IngestionEvent } from "./types";

const now = Date.UTC(2025, 0, 18, 8, 42, 0);
function ago(min: number): string {
  return new Date(now - min * 60000).toISOString();
}

export const DATA_SOURCES: DataSource[] = [
  {
    id: "src-s2",
    name: "Sentinel-2 L2A (Optical)",
    category: "optical",
    provider: "ESA / Copernicus",
    status: "healthy",
    resolution: "10 m",
    cadence: "5 days",
    lastSync: ago(38),
    coverage: "National (full)",
    records: 184320,
    freshnessMin: 38,
    latencyMs: 4200,
    storageTB: 12.4,
    license: "Copernicus Open",
    description: "Multispectral optical surface reflectance, 13 bands. Primary input for NDVI, NDWI, NBR, turbidity and land-cover change.",
  },
  {
    id: "src-s1",
    name: "Sentinel-1 GRD (SAR)",
    category: "sar",
    provider: "ESA / Copernicus",
    status: "healthy",
    resolution: "10–20 m",
    cadence: "6 days",
    lastSync: ago(72),
    coverage: "National (full)",
    records: 96440,
    freshnessMin: 72,
    latencyMs: 6800,
    storageTB: 8.1,
    license: "Copernicus Open",
    description: "C-band SAR (VV+VH). Cloud-independent observation for excavation signatures, coherence change, flood mapping and surface deformation.",
  },
  {
    id: "src-l8",
    name: "Landsat 8/9 L2",
    category: "optical",
    provider: "USGS / NASA",
    status: "healthy",
    resolution: "30 m",
    cadence: "8 days (combined)",
    lastSync: ago(180),
    coverage: "National",
    records: 41200,
    freshnessMin: 180,
    latencyMs: 9200,
    storageTB: 3.2,
    license: "Public Domain",
    description: "Long-archive optical (1984→present). Enables decadal trend baselines and cross-validation of Sentinel-2 detections.",
  },
  {
    id: "src-modis",
    name: "MODIS (Terra + Aqua)",
    category: "optical",
    provider: "NASA LP DAAC",
    status: "healthy",
    resolution: "250–500 m",
    cadence: "Daily",
    lastSync: ago(14),
    coverage: "National",
    records: 87600,
    freshnessMin: 14,
    latencyMs: 2100,
    storageTB: 1.8,
    license: "Public Domain",
    description: "Daily coarse-resolution for rapid phenology, active fire (VIIRS/MODIS), and broad land-surface temperature.",
  },
  {
    id: "src-srtm",
    name: "SRTM DEM",
    category: "dem",
    provider: "NASA / USGS",
    status: "healthy",
    resolution: "30 m",
    cadence: "Static (2000)",
    lastSync: ago(525600),
    coverage: "National",
    records: 1,
    freshnessMin: 525600,
    latencyMs: 0,
    storageTB: 0.4,
    license: "Public Domain",
    description: "Shuttle Radar Topography elevation baseline for terrain, slope, watershed delineation and viewshed.",
  },
  {
    id: "src-copdem",
    name: "Copernicus DEM GLO-30",
    category: "dem",
    provider: "ESA / Copernicus",
    status: "healthy",
    resolution: "30 m",
    cadence: "Static (2021)",
    lastSync: ago(525600),
    coverage: "National",
    records: 1,
    freshnessMin: 525600,
    latencyMs: 0,
    storageTB: 0.5,
    license: "Copernicus Open",
    description: "Higher-accuracy global DEM. Used for hydrological flow modelling, hillshade, and infrastructure siting.",
  },
  {
    id: "src-dw",
    name: "Dynamic World",
    category: "landcover",
    provider: "Google + WRI",
    status: "healthy",
    resolution: "10 m",
    cadence: "5 days",
    lastSync: ago(40),
    coverage: "National",
    records: 92160,
    freshnessMin: 40,
    latencyMs: 3100,
    storageTB: 2.6,
    license: "CC-BY-4.0",
    description: "Near-real-time 9-class land cover probabilities. Primary feed for built-up growth and broad LCC.",
  },
  {
    id: "src-wc",
    name: "ESA WorldCover",
    category: "landcover",
    provider: "ESA",
    status: "syncing",
    resolution: "10 m",
    cadence: "Annual",
    lastSync: ago(320),
    coverage: "National",
    records: 46080,
    freshnessMin: 320,
    latencyMs: 5400,
    storageTB: 1.9,
    license: "CC-BY-4.0",
    description: "Annual validated 11-class land cover. Cross-validates Dynamic World and provides authoritative yearly snapshot.",
  },
  {
    id: "src-gfc",
    name: "Global Forest Change",
    category: "landcover",
    provider: "Hansen / UMD",
    status: "healthy",
    resolution: "30 m",
    cadence: "Annual",
    lastSync: ago(640),
    coverage: "National",
    records: 18400,
    freshnessMin: 640,
    latencyMs: 1800,
    storageTB: 0.9,
    license: "CC-BY-4.0",
    description: "Tree-cover loss/gain year layers (2000→present). Baseline for deforestation confidence scoring.",
  },
  {
    id: "src-chirps",
    name: "CHIRPS Rainfall",
    category: "weather",
    provider: "UCSB Climate Hazards",
    status: "healthy",
    resolution: "5 km",
    cadence: "Daily",
    lastSync: ago(22),
    coverage: "National",
    records: 3840,
    freshnessMin: 22,
    latencyMs: 900,
    storageTB: 0.2,
    license: "Public Domain",
    description: "Quasi-global daily rainfall. Disambiguates climate-driven vs anthropogenic change and informs turbidity causality.",
  },
  {
    id: "src-era5",
    name: "ERA5 Reanalysis",
    category: "weather",
    provider: "ECMWF / Copernicus CDS",
    status: "healthy",
    resolution: "31 km",
    cadence: "Hourly",
    lastSync: ago(8),
    coverage: "National",
    records: 161280,
    freshnessMin: 8,
    latencyMs: 1400,
    storageTB: 1.1,
    license: "Copernicus Open",
    description: "Atmospheric reanalysis: temperature, humidity, soil moisture, wind. Environmental context for change attribution.",
  },
  {
    id: "src-osm",
    name: "OpenStreetMap",
    category: "infrastructure",
    provider: "OSM Community",
    status: "healthy",
    resolution: "Vector",
    cadence: "Minutely diff",
    lastSync: ago(6),
    coverage: "National",
    records: 2840000,
    freshnessMin: 6,
    latencyMs: 400,
    storageTB: 0.7,
    license: "ODbL",
    description: "Roads, buildings, points of interest. Baseline vector infrastructure; diffed against imagery to detect new roads & structures.",
  },
  {
    id: "src-hydro",
    name: "HydroSHEDS",
    category: "hydrology",
    provider: "WWF / USGS",
    status: "healthy",
    resolution: "15 arc-sec",
    cadence: "Static",
    lastSync: ago(525600),
    coverage: "National",
    records: 1,
    freshnessMin: 525600,
    latencyMs: 0,
    storageTB: 0.3,
    license: "CC-BY-NC-SA",
    description: "River networks, watersheds, flow accumulation. Foundation for hydrology and river-morphology reasoning.",
  },
  {
    id: "src-wdpa",
    name: "Protected Areas (WDPA)",
    category: "environmental",
    provider: "UNEP-WCMC",
    status: "healthy",
    resolution: "Vector",
    cadence: "Monthly",
    lastSync: ago(9000),
    coverage: "National",
    records: 312,
    freshnessMin: 9000,
    latencyMs: 600,
    storageTB: 0.05,
    license: "Restricted",
    description: "World Database on Protected Areas. Boundary reference for reserve-encroachment observations.",
  },
  {
    id: "src-ghadmin",
    name: "Ghana Administrative Boundaries",
    category: "administrative",
    provider: "Ghana Statistical Service",
    status: "healthy",
    resolution: "Vector",
    cadence: "Annual",
    lastSync: ago(28800),
    coverage: "National",
    records: 16,
    freshnessMin: 28800,
    latencyMs: 300,
    storageTB: 0.04,
    license: "Open Government",
    description: "16 regions, 261 districts, electoral areas. Spatial join target for all entity/observation rollups.",
  },
  {
    id: "src-planet",
    name: "Planet Tasking (pilot)",
    category: "optical",
    provider: "Planet Labs",
    status: "degraded",
    resolution: "3 m",
    cadence: "Daily (tasked)",
    lastSync: ago(540),
    coverage: "Western belt only",
    records: 4200,
    freshnessMin: 540,
    latencyMs: 12000,
    storageTB: 0.8,
    license: "Commercial (trial)",
    description: "High-resolution commercial optical for verification of critical observations. Pilot integration; degraded due to API quota.",
  },
];

export const INGESTION_LOG: IngestionEvent[] = [
  { id: "ing-1", time: ago(6), source: "OpenStreetMap", action: "minutely diff apply", status: "ok", detail: "+2,184 features, 1,902 modified" },
  { id: "ing-2", time: ago(8), source: "ERA5 Reanalysis", action: "hourly ingest", status: "ok", detail: "168 timesteps, t+0 = 08:00 UTC" },
  { id: "ing-3", time: ago(14), source: "MODIS", action: "daily composite", status: "ok", detail: "tile 074018 / 075018 complete" },
  { id: "ing-4", time: ago(22), source: "CHIRPS Rainfall", action: "daily ingest", status: "ok", detail: "national mosaic, 0 missing pixels" },
  { id: "ing-5", time: ago(38), source: "Sentinel-2 L2A", action: "scene ingest + tile", status: "ok", detail: "4 scenes, cloud-mask 12.4%" },
  { id: "ing-6", time: ago(40), source: "Dynamic World", action: "probability cube append", status: "ok", detail: "4 tiles synced" },
  { id: "ing-7", time: ago(72), source: "Sentinel-1 GRD", action: "scene ingest + coherence", status: "warn", detail: "1 scene partial (orbit gap), retry queued" },
  { id: "ing-8", time: ago(180), source: "Landsat 8/9 L2", action: "scene ingest", status: "ok", detail: "2 scenes, path/row 194/055" },
  { id: "ing-9", time: ago(320), source: "ESA WorldCover", action: "annual layer rebuild", status: "warn", detail: "validation running, 84% complete" },
  { id: "ing-10", time: ago(540), source: "Planet Tasking", action: "quota-exceeded", status: "err", detail: "API 429; backoff to 6h interval" },
  { id: "ing-11", time: ago(120), source: "gdt-cv-excav-v4.2", action: "inference batch", status: "ok", detail: "western belt, 412 tiles, 8 detections" },
  { id: "ing-12", time: ago(96), source: "gdt-cv-defor-v3.4", action: "inference batch", status: "ok", detail: "forest belt, 288 tiles, 3 detections" },
  { id: "ing-13", time: ago(60), source: "gdt-hydro-turb-v2.1", action: "river reach scan", status: "ok", detail: "Pra/Ankobra/Tano, 2 anomalies" },
];
