// Ghana Digital Twin — Dataset Source Catalog
// Authoritative registry of all datasets the platform integrates.
// Each entry has full provenance. Real connectors fetch live data; metadata
// connectors record provenance + health for bulk/raster datasets that require
// offline ingest tooling (documented in description).

import type { DatasetSourceRecord, SourceCategory } from "./types";

export const DATASET_CATALOG: DatasetSourceRecord[] = [
  // ===== Administrative (real, live-fetched) =====
  {
    sourceId: "geoboundaries",
    name: "geoBoundaries (GHA)",
    category: "administrative",
    provider: " William & Mary geoBoundaries",
    license: "CC-BY-SA 2.0 (via OSM)",
    resolution: "Vector (ADM0/1/2)",
    cadence: "On release (annual)",
    coverage: "National · 16 regions + districts",
    description: "Authoritative administrative boundaries for Ghana (regions ADM1, districts ADM2). Live-fetched from the geoBoundaries API. Primary source for region/district entities and spatial joins.",
    storageType: "vector",
    status: "pending",
    recordCount: 0,
    metadata: { endpoint: "https://www.geoboundaries.org/api/current/gbOpen/GHA/" },
  },
  {
    sourceId: "gadm",
    name: "GADM Ghana",
    category: "administrative",
    provider: "GADM",
    license: "Non-commercial",
    resolution: "Vector (ADM0–3)",
    cadence: "Static (v4.1)",
    coverage: "National",
    description: "Global Administrative Areas database. Alternative/cross-validation admin boundary source. Connector registered; bulk extract requires offline download.",
    storageType: "vector",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://gadm.org/download_country.html" },
  },
  {
    sourceId: "naturalearth",
    name: "Natural Earth",
    category: "administrative",
    provider: "NACIS",
    license: "Public Domain",
    resolution: "Vector (1:10m / 1:50m)",
    cadence: "Static",
    coverage: "National (country outline)",
    description: "Public-domain country + coastline vectors. Used for the national outline and coastline reference.",
    storageType: "vector",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://www.naturalearthdata.com/" },
  },

  // ===== Hydrology =====
  {
    sourceId: "hydrosheds",
    name: "HydroSHEDS",
    category: "hydrology",
    provider: "WWF / USGS",
    license: "CC-BY-NC-SA 3.0",
    resolution: "15 arc-sec (~500m)",
    cadence: "Static (v1)",
    coverage: "National (river networks, watersheds)",
    description: "River networks, flow accumulation, and watershed delineation. Foundation for hydrology reasoning and river-morphology analysis. Connector registered; raster/vector bulk extract requires offline download from hydrosheds.org.",
    storageType: "vector",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://www.hydrosheds.org/" },
  },
  {
    sourceId: "hydrorivers",
    name: "HydroRIVERS",
    category: "hydrology",
    provider: "WWF / USGS",
    license: "CC-BY-NC-SA 3.0",
    resolution: "Vector (~500m)",
    cadence: "Static",
    coverage: "National",
    description: "Vector river network derived from HydroSHEDS. Provides ordered stream lines with Strahler order. Bulk extract via hydrosheds.org.",
    storageType: "vector",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://www.hydrosheds.org/products/hydrorivers" },
  },
  {
    sourceId: "jrc-gsw",
    name: "JRC Global Surface Water",
    category: "hydrology",
    provider: "EC JRC / Google",
    license: "CC-BY-4.0",
    resolution: "30 m",
    cadence: "Annual + monthly",
    coverage: "National",
    description: "Surface water occurrence, recurrence, seasonality and transitions (1984–2021). Powers water-body extent and seasonal water detection. Bulk via GEE.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://global-surface-water.appspot.com/" },
  },

  // ===== Elevation =====
  {
    sourceId: "copernicus-dem",
    name: "Copernicus DEM GLO-30",
    category: "dem",
    provider: "ESA / Copernicus",
    license: "Copernicus Open",
    resolution: "30 m",
    cadence: "Static (2021)",
    coverage: "National",
    description: "High-accuracy global digital elevation model. Terrain, slope, watershed delineation, viewshed. Bulk via Copernicus Space Hub.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://spacedata.copernicus.eu/web/cscda/data-access" },
  },
  {
    sourceId: "srtm",
    name: "SRTM",
    category: "dem",
    provider: "NASA / USGS",
    license: "Public Domain",
    resolution: "30 m",
    cadence: "Static (2000)",
    coverage: "National",
    description: "Shuttle Radar Topography Mission elevation baseline. Long-term terrain reference. Bulk via USGS EarthExplorer.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://earthexplorer.usgs.gov/" },
  },

  // ===== Land Cover =====
  {
    sourceId: "esa-worldcover",
    name: "ESA WorldCover",
    category: "landcover",
    provider: "ESA",
    license: "CC-BY-4.0",
    resolution: "10 m",
    cadence: "Annual (2020/2021)",
    coverage: "National",
    description: "Validated 11-class land cover. Authoritative yearly snapshot; cross-validates Dynamic World. Bulk via ESA WorldCover portal.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://esa-worldcover.org/" },
  },
  {
    sourceId: "dynamic-world",
    name: "Dynamic World",
    category: "landcover",
    provider: "Google + WRI",
    license: "CC-BY-4.0",
    resolution: "10 m",
    cadence: "5 days",
    coverage: "National",
    description: "Near-real-time 9-class land-cover probabilities. Primary feed for built-up growth and broad LCC. Accessible via GEE / Earth Engine API.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://dynamicworld.app/" },
  },

  // ===== Forest =====
  {
    sourceId: "hansen-gfc",
    name: "Global Forest Change (Hansen)",
    category: "forest",
    provider: "UMD / Google / USGS",
    license: "CC-BY-4.0",
    resolution: "30 m",
    cadence: "Annual",
    coverage: "National",
    description: "Tree-cover loss/gain year layers (2000→present). Baseline for deforestation confidence scoring. Bulk via GLAD/UMD.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://glad.earthengine.app/view/global-forest-change" },
  },

  // ===== Infrastructure (real, live-fetched via OSM Overpass) =====
  {
    sourceId: "osm-overpass",
    name: "OpenStreetMap (Overpass)",
    category: "infrastructure",
    provider: "OSM Community",
    license: "ODbL",
    resolution: "Vector",
    cadence: "On-demand (minutely diff available)",
    coverage: "National (roads, railways, settlements, dams, bridges)",
    description: "Live OpenStreetMap features fetched via Overpass API. Provides roads, railways, settlements, dams, bridges, and points of interest. Diffed against imagery to detect new infrastructure.",
    storageType: "vector",
    status: "pending",
    recordCount: 0,
    metadata: { endpoint: "https://overpass-api.de/api/interpreter" },
  },

  // ===== Protected Areas =====
  {
    sourceId: "wdpa",
    name: "WDPA Protected Areas",
    category: "environmental",
    provider: "UNEP-WCMC",
    license: "Restricted (WDPA Terms)",
    resolution: "Vector",
    cadence: "Monthly",
    coverage: "National",
    description: "World Database on Protected Areas. Boundary reference for reserve-encroachment observations. Bulk via protectedplanet.net (requires registration).",
    storageType: "vector",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://www.protectedplanet.net/" },
  },

  // ===== Settlements / Population =====
  {
    sourceId: "ghsl",
    name: "GHSL (Global Human Settlement)",
    category: "settlement",
    provider: "EC JRC",
    license: "CC-BY-4.0",
    resolution: "100 m / 1 km",
    cadence: "Multi-year (1975–2030)",
    coverage: "National",
    description: "Built-up surface and settlement layers. Cross-validates OSM settlements + Dynamic World built class. Bulk via JRC GHSL portal.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://human-settlement.emergency.copernicus.eu/" },
  },
  {
    sourceId: "worldpop",
    name: "WorldPop",
    category: "population",
    provider: "WorldPop / Univ. Southampton",
    license: "CC-BY-4.0",
    resolution: "100 m",
    cadence: "Annual",
    coverage: "National",
    description: "Gridded population estimates. Population context for settlements and impact assessment. Bulk via worldpop.org.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://www.worldpop.org/" },
  },

  // ===== Weather =====
  {
    sourceId: "chirps",
    name: "CHIRPS Rainfall",
    category: "weather",
    provider: "UCSB Climate Hazards Center",
    license: "Public Domain",
    resolution: "5 km",
    cadence: "Daily",
    coverage: "National",
    description: "Quasi-global daily rainfall. Disambiguates climate-driven vs anthropogenic change and informs turbidity causality. Bulk via UCSB CHIRPS.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://www.chc.ucsb.edu/data/chirps" },
  },
  {
    sourceId: "era5",
    name: "ERA5 Reanalysis",
    category: "weather",
    provider: "ECMWF / Copernicus CDS",
    license: "Copernicus Open",
    resolution: "31 km",
    cadence: "Hourly",
    coverage: "National",
    description: "Atmospheric reanalysis: temperature, humidity, soil moisture, wind. Environmental context for change attribution. Bulk via CDS API.",
    storageType: "raster",
    status: "pending",
    recordCount: 0,
    metadata: { url: "https://cds.climate.copernicus.eu/" },
  },
];

export function getCatalogEntry(sourceId: string): DatasetSourceRecord | undefined {
  return DATASET_CATALOG.find((s) => s.sourceId === sourceId);
}

export const LIVE_CONNECTORS = ["geoboundaries", "osm-overpass"] as const;
export type LiveConnectorId = (typeof LIVE_CONNECTORS)[number];
